version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/hxzydb?schema=public
      - NODE_ENV=production
    depends_on:
      - db
    restart: always

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=hxzydb
    restart: always

volumes:
  postgres_data: 