services:
  db:
    image: postgres:15-alpine # 使用最新稳定版的 PostgreSQL 镜像
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hxzydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qq.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80" # 默认pgAdmin端口是80, 映射到主机的5050端口
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: