# 使用 PostgreSQL 14 作为基础镜像
FROM postgres:14-alpine

# 设置环境变量
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=hxzydb

# 复制初始化脚本（如果有的话）
COPY ./prisma/init.sql /docker-entrypoint-initdb.d/

# 暴露 PostgreSQL 默认端口
EXPOSE 5432 